---
- name: Change Default interfaces configurations
  hosts: chassis1
  remote_user: root
  strategy: free
  tasks:
  - name: Delete extra vNIC on vDCMs
    file:
      state: absent
      path: "/etc/sysconfig/network-scripts/ifcfg-enp13s0"
  - name: List all interfaces in host
    command: find /etc/sysconfig/network-scripts/ -name "ifcfg-enp*"
    register: host_interfaces
  - name: Replace DHCP info on ifcfg-enp*
    replace:
      path={{item}}
      regexp='BOOTPROTO=dhcp'
      replace='BOOTPROTO=static'
    with_items: "{{ host_interfaces.stdout_lines }}"
  - name: Replace IPV4 Failure Fatal on IPV4
    replace:
      path={{item}}
      regexp='IPV4_FAILURE_FATAL=no'
      replace='IPV4_FAILURE_FATAL=yes'
    with_items: "{{ host_interfaces.stdout_lines }}"
  - name: Set IP as IPv4
    replace:
      path={{item}}
      regexp='IPV6INIT=yes'
      replace='IPV6INIT=no'
    with_items: "{{ host_interfaces.stdout_lines }}"
  - name: Set Interface on Boot
    replace:
      path={{item}}
      regexp='ONBOOT=no'
      replace='ONBOOT=yes'
    with_items: "{{ host_interfaces.stdout_lines }}"
  - name: Look Up for Input_IP
    set_fact: ip_input="{{ lookup('csvfile', '{{item}} file=ansible.csv delimiter=, col=1') }}"
    with_items: "{{ ansible_default_ipv4.address }}"
  - name: Insert IPADDRESS_INPUT into file
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-enp7s0
      insertafter: 'EOF'
      line: "IPADDR={{ip_input}}"
  - name: Look Up for Prefix
    set_fact: ip_input_prefix="{{ lookup('csvfile', '{{item}} file=ansible.csv delimiter=, col=2') }}"
    with_items: "{{ ansible_default_ipv4.address }}"
  - name: Insert PREFIX_INPUT into file
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-enp7s0
      insertafter: 'EOF'
      line: "PREFIX={{ip_input_prefix}}"
  - name: Look Up for Output_IP
    set_fact: ip_output="{{ lookup('csvfile', '{{item}} file=ansible.csv delimiter=, col=3') }}"
    with_items: "{{ ansible_default_ipv4.address }}"
  - name: Insert IPADDRESS_OUPTUT into file
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-enp12s0
      insertafter: 'EOF'
      line: "IPADDR={{ip_output}}"
  - name: Look Up for Prefix
    set_fact: ip_output_prefix="{{ lookup('csvfile', '{{item}} file=ansible.csv delimiter=, col=4') }}"
    with_items: "{{ ansible_default_ipv4.address }}"
  - name: Insert PREFIX_OUTPUT into file
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-enp12s0
      insertafter: 'EOF'
      line: "PREFIX={{ip_output_prefix}}"
  - name: Change RP Filter for Input Traffic Port
    lineinfile:
      path: /etc/sysctl.conf
      insertafter: 'EOF'
      line: "net.ipv4.conf.enp7s0.rp_filter=2"
  - name: Change RP Fier for Output Traffic Port
    lineinfile:
      path: /etc/sysctl.conf
      insertafter: 'EOF'
      line: "net.ipv4.conf.enp12s0.rp_filter=2"
  - name: Restart Sysctl
    command: sysctl -p
  - name: Restart network service
    command: service network restart
    args:
      warn: false
