---
- name: Move and run vDCM script
  hosts: chassis1
  remote_user: root
  strategy: free
  tasks:
  - name: Creates /temps/ directory
    file: path=/temps state=directory
  - name: Disable Firewall on Hosts
    command: systemctl disable firewalld
  - name: Stop Firewall on Hosts
    command: systemctl stop firewalld
  - name: Copy SW from localhost to vdcm group
    copy:
       src: /Users/carlrod2/vdcm-installer-7.0.1-215.sh
       dest: /temps
       owner: root
       group: root
       mode: 0777
  - name: Run vDCM installation
    command: /temps/vdcm-installer-7.0.1-215.sh
    register: vdcm_install_out
  - debug: var=vdcm_install_out.stdout_lines
  - name: Enable to run all vDCM services
    command: /opt/cisco/vdcm/bin/vdcm-configure service --enable --all
    register: vdcm_enable_all
  - debug: var=vdcm_enable_all.stdout_lines
  - name: Stop vDCM software
    command: /opt/cisco/vdcm/bin/vdcm-configure service --stop
    register: vdcm_service_stop
  - debug: var=vdcm_service_stop.stdout_lines
  - name: Add IIOP user for VSM
    command: /opt/cisco/vdcm/bin/vdcm-configure iiop-user --add IZZI-ADMIN --password C15c0123
  - name: Stop again vDCM software
    command: /opt/cisco/vdcm/bin/vdcm-configure service --stop
    register: vdcm_service_stop
  - debug: var=vdcm_service_stop.stdout_lines
  - name: Comment existing NTP servers
    replace:
      path: /etc/ntp.conf
      regexp: '^server'
      replace: '#server'
  - name: Update /etc/ntp.conf file
    lineinfile:
      path: /etc/ntp.conf
      regexp: '^server(.*)'
      insertafter: '(^)#server(.*)'
      line: 'server 10.240.110.100'
  - name: Restart ntpd service
    command: service ntpd restart
    args:
      warn: false
  - name: Debug NTP State
    command: ntpq -p
    register: ntpq_out
  - debug: var=ntpq_out.stdout_lines
  - name: Fix warnings
    command: /opt/cisco/vdcm/bin/vdcm-configure -v fix --warnings
    register: vdcm_fix_warnings
  - debug: var=vdcm_fix_warnings.stdout_lines
  - name: Change MaxCrashReportsSize /etc/abrt/abrt.conf to 8000
    replace:
      path: /etc/abrt/abrt.conf
      regexp: '^MaxCrashReportsSize(.*)'
      replace: 'MaxCrashReportsSize = 8000'
  - name: Comment RateLimitInterval on journald.conf
    replace:
      path: /etc/systemd/journald.conf
      regexp: '^RateLimitInterval=(.*)'
      replace: '#RateLimitInterval=60s'
  - name: Comment RateLimitBurst on journald.conf
    replace:
      path: /etc/systemd/journald.conf
      regexp: '^RateLimitBurst=(.*)'
      replace: '#RateLimitBurst=1818'
